config/routes.rb
Rails.application.routes.draw do
  resources :jokers
  resources :avoidances
  resources :otetsukis
  resources :criticals
  resources :grades_tournaments
  resources :districts
  resources :hands
  resources :genders
  resources :grades
  resources :age_classes
  resources :areas
  resources :styles
  resources :game_counts
  resources :game_types
  resources :fields
  resources :karuta
  resources :opponents
  resources :results
  resources :tournaments
  resources :schedule_tournaments
  resources :schedule_practices
  devise_for :users
  root 'pages#index'
  get 'pages/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/age_class.rb
class AgeClass < ApplicationRecord
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/avoidance.rb
class Avoidance < ApplicationRecord
  belongs_to :result
  belongs_to :karutum
end

app/models/critical.rb
class Critical < ApplicationRecord
  belongs_to :result
  belongs_to :karutum
  belongs_to :field
end

app/models/district.rb
class District < ApplicationRecord
end

app/models/field.rb
class Field < ApplicationRecord
  has_many :criticals
  has_many :results, :through => :criticals
  has_many :karutum, :through => :criticals
  has_many :otetsukis
  has_many :results, :through => :otetsukis
  has_many :karutum, :through => :otetsukis
end

app/models/game_count.rb
class GameCount < ApplicationRecord
    has_many :results
end

app/models/game_type.rb
class GameType < ApplicationRecord
    has_many :results
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :grades_tournaments
  has_many :tournaments, :through => :grades_tournaments
end

app/models/hand.rb
class Hand < ApplicationRecord
end

app/models/joker.rb
class Joker < ApplicationRecord
  belongs_to :result
  belongs_to :karuta
end

app/models/karutum.rb
class Karutum < ApplicationRecord
    has_many :avoidances
    has_many :results, :through => :avoidances
    has_many :jokers
    has_many :results, :through => :jokers
    has_many :criticals
    has_many :results, :through => :criticals
    has_many :fields, :through => :criticals
    has_many :otetsukis
    has_many :results, :through => :otetsukis
    has_many :fields, :through => :otetsukis
end

app/models/opponent.rb
class Opponent < ApplicationRecord
    has_many :results
    belongs_to :style
    belongs_to :gender
    belongs_to :hand
    belongs_to :ageClass
end

app/models/otetsuki.rb
class Otetsuki < ApplicationRecord
  belongs_to :result
  belongs_to :karutum
  belongs_to :field
end

app/models/result.rb
class Result < ApplicationRecord
    has_many :avoidances, dependent: :destroy
    has_many :karuta, :through => :avoidances
    accepts_nested_attributes_for :avoidances, allow_destroy: true
    has_many :jokers, dependent: :destroy
    has_many :karuta, :through => :jokers
    accepts_nested_attributes_for :jokers, allow_destroy: true
    has_many :criticals, dependent: :destroy
    has_many :karuta, :through => :criticals
    has_many :fields, :through => :criticals
    accepts_nested_attributes_for :criticals, allow_destroy: true
    has_many :otetsukis, dependent: :destroy
    has_many :karuta, :through => :otetsukis
    has_many :fields, :through => :otetsukis
    accepts_nested_attributes_for :otetsukis, allow_destroy: true
    belongs_to :gameType
    belongs_to :gameCount
    belongs_to :opponent
    belongs_to :user
end

app/models/style.rb
class Style < ApplicationRecord
    has_many :opponents
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  default_scope -> { order(date: :asc) }
  has_many :grades_tournament
  has_many :tournaments, :through => :grades_tournament
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/shared/_header.html.erb
<header>
  <nav>
    <div class="header-title header-disp">
      <%= link_to 'かるたカレンダー', schedule_practices_path, class: "header-link" %>
    </div>
    <% if user_signed_in? %>
    <ul class="header-list">
      <li class="header-disp"><%= link_to '結果一覧', results_path, class: "header-link" %></li>
      <li class="header-disp"><%= link_to '大会情報', tournaments_path, class: "header-link" %></li>
      <li class="header-disp"><%= link_to 'プロフィール変更', edit_user_registration_path, class: "header-link" %></li>
      <li class="header-disp"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "header-link" %></li>
    </ul>
    <% else %>
    <ul class="header-list header-disp">
      <li class="header-disp"><%= link_to '結果入力', new_result_path, class: "header-link" %></li>
      <li class="header-disp"><%= link_to '結果一覧', results_path, class: "header-link" %></li>
      <li class="header-disp"><%= link_to '大会情報', tournaments_path, class: "header-link" %></li>
      <li class="header-disp"><%= link_to 'サインアップ', new_user_registration_path, class: "header-link" %></li>
      <li class="header-disp"><%= link_to 'ログイン', new_user_session_path, class: "header-link" %></li>
    </ul>
    <% end %>
  </nav>
</header>