config/routes.rb
Rails.application.routes.draw do
  resources :jokers
  resources :avoidances
  resources :otetsukis
  resources :criticals
  resources :grades_tournaments
  resources :districts
  resources :hands
  resources :genders
  resources :grades
  resources :age_classes
  resources :areas
  resources :styles
  resources :game_counts
  resources :game_types
  resources :fields
  resources :karuta
  resources :opponents
  resources :results
  resources :tournaments
  resources :schedule_tournaments
  resources :schedule_practices
  devise_for :users
  root 'pages#index'
  get 'pages/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/age_class.rb
class AgeClass < ApplicationRecord
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/avoidance.rb
class Avoidance < ApplicationRecord
  belongs_to :result
  belongs_to :karutum
end

app/models/critical.rb
class Critical < ApplicationRecord
  belongs_to :result
  belongs_to :karutum
  belongs_to :field
end

app/models/district.rb
class District < ApplicationRecord
end

app/models/field.rb
class Field < ApplicationRecord
  has_many :criticals
  has_many :results, :through => :criticals
  has_many :karutum, :through => :criticals
  has_many :otetsukis
  has_many :results, :through => :otetsukis
  has_many :karutum, :through => :otetsukis
end

app/models/game_count.rb
class GameCount < ApplicationRecord
    has_many :results
end

app/models/game_type.rb
class GameType < ApplicationRecord
    has_many :results
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :grades_tournaments
  has_many :tournaments, :through => :grades_tournaments
end

app/models/hand.rb
class Hand < ApplicationRecord
end

app/models/joker.rb
class Joker < ApplicationRecord
  belongs_to :result
  belongs_to :karuta
end

app/models/karutum.rb
class Karutum < ApplicationRecord
    has_many :avoidances
    has_many :results, :through => :avoidances
    has_many :jokers
    has_many :results, :through => :jokers
    has_many :criticals
    has_many :results, :through => :criticals
    has_many :fields, :through => :criticals
    has_many :otetsukis
    has_many :results, :through => :otetsukis
    has_many :fields, :through => :otetsukis
end

app/models/opponent.rb
class Opponent < ApplicationRecord
    has_many :results
    belongs_to :style
    belongs_to :gender
    belongs_to :hand
    belongs_to :ageClass
end

app/models/otetsuki.rb
class Otetsuki < ApplicationRecord
  belongs_to :result
  belongs_to :karutum
  belongs_to :field
end

app/models/result.rb
class Result < ApplicationRecord
    has_many :avoidances, dependent: :destroy
    has_many :karuta, :through => :avoidances
    accepts_nested_attributes_for :avoidances, allow_destroy: true
    has_many :jokers, dependent: :destroy
    has_many :karuta, :through => :jokers
    accepts_nested_attributes_for :jokers, allow_destroy: true
    has_many :criticals, dependent: :destroy
    has_many :karuta, :through => :criticals
    has_many :fields, :through => :criticals
    accepts_nested_attributes_for :criticals, allow_destroy: true
    has_many :otetsukis, dependent: :destroy
    has_many :karuta, :through => :otetsukis
    has_many :fields, :through => :otetsukis
    accepts_nested_attributes_for :otetsukis, allow_destroy: true
    belongs_to :gameType
    belongs_to :gameCount
    belongs_to :opponent
    belongs_to :user
end

app/models/style.rb
class Style < ApplicationRecord
    has_many :opponents
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  default_scope -> { order(date: :asc) }
  has_many :grades_tournament
  has_many :tournaments, :through => :grades_tournament
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:date, :gameType_id, :gameCount_id, :opponent_id, :cardDifference, :comment, :discussionOpp, :discussionSelf, :user_id, :critical_id, :avoidance_id, :otetsuki_id, :joker_id)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/hands_helper.rb
module HandsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_with(model: result, local: true) do |form| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-form">
    <div class="result-input-container result-main">
      <h2>試合結果</h2>
      <div class="field">
        <p>練習／大会／指導(*)</p>
        <% GameType.all.each do |attr| %>
          <div>
            <%= form.radio_button 'gameType_id', attr.id, {} %><%= attr.name %>
          </div>
        <% end %>
        <div class="sub-field taikai-names" id="inputtaikai">
          <p>大会名</p>
          <select name="taikai" id="" class="taikai-name">
            <option value="" hidden>予定表に登録している大会名を選択</option>
            <option value="1">広島大会</option>
            <option value="2">吉野会大会</option>
          </select>
        </div>
      </div>

      <div class="field">
        <p>日付(*)</p>
        <div><%= form.date_select :date %></div>
      </div>

      <div class="field">
        <p>場所</p>
        <div class="text-field"><%= form.text_field :place %></div>
        <!-- placeは後で追加        -->
        <!-- ※大会名が選択されたら自動入力されるようにする -->
      </div>

      <div class="field">
        <p>何試合目か</p>
        <%= form.number_field :gameCount_id, options = {min: 1} %>試合目
      </div>

      <div class="field">
        <p>勝敗(*)</p>
        <div class="win-lose-radio radio">
          <input type="radio" name="win-lose" class="win-lose-input" id="win">
          <label for="win">勝ち</label>
          <input type="radio" name="win-lose" class="win-lose-input" id="lose">
          <label for="lose">負け</label>
        </div>
        <!-- 勝ちでcard-differenceがプラス、負けでマイナスにする -->
      </div>

      <div class="field">
        <p>枚数差</p>
        <%= form.number_field :cardDifference, options = {min: 1} %>枚差
      </div>
    </div>

    <div class="result-input-container result-detail">
      <h2>試合結果詳細</h2>
      <div class="field otetsuki">
        <p>お手つき回数</p>
        <%= form.number_field :otetsuki, options = {min: 0} %>回
        <div class="sub-field 1 2 3 4 5 6 7 8 9 10">
          <p>1枚目</p>
          <%= form.fields_for :otetsukis do |otetsuki| %>
            <%= otetsuki.collection_checkboxes :result_id, Karuta.all %>
          <%- end %>
          <select name="karuta-ote1" id="" class="karuta-ote">
            <option value="" hidden>札を選ぶ</option>
            <option value="1">あきの</option>
            <option value="2">はるす</option>
            <option value="3">あし</option>
            <option value="4">たご</option>
            <option value="5">おく</option>
            <option value="6">かさ</option>
            <option value="7">あまの</option>
            <option value="8">わがい</option>
            <option value="9">はなの</option>
            <option value="10">これ</option>
          </select>
        </div>
        <div class="sub-field 2 3 4 5 6 7 8 9 10">
          <p>2枚目</p>
          <select name="karuta-ote2" id="" class="karuta-ote">
            <option value="" hidden>札を選ぶ</option>
            <option value="1">あきの</option>
            <option value="2">はるす</option>
            <option value="3">あし</option>
            <option value="4">たご</option>
            <option value="5">おく</option>
            <option value="6">かさ</option>
            <option value="7">あまの</option>
            <option value="8">わがい</option>
            <option value="9">はなの</option>
            <option value="10">これ</option>
          </select>
        </div>
      </div>

      <div class="field discussion-self">
        <p>もめ回数（自分から）</p>
        <%= form.number_field :discussionSelf, options = {min: 0} %>回
      </div>

      <div class="field discussion-opp">
        <p>もめ回数（相手から）</p>
        <%= form.number_field :discussionOpp, options = {min: 0} %>回
      </div>

      <div class="field critical">
        <p>うまく取れた札（枚数）</p>
        <%= form.number_field :critical, options = {min: 0} %>枚
      </div>

      <div class="field avoidance">
        <p>うまく避けれた札（枚数）</p>
        <%= form.number_field :avoidance, options = {min: 0} %>枚
      </div>

      <div class="field joker">
        <p>ばば（運命戦の場合）</p>
        <select name="karuta-joker" id="" class="karuta-joker">
          <option value="" hidden>札を選ぶ</option>
          <option value="1">あきの</option>
          <option value="2">はるす</option>
          <option value="3">あし</option>
          <option value="4">たご</option>
          <option value="5">おく</option>
          <option value="6">かさ</option>
          <option value="7">あまの</option>
          <option value="8">わがい</option>
          <option value="9">はなの</option>
          <option value="10">これ</option>
        </select>
      </div>
    </div>

    <div class="result-input-container result-opp">
      <h2>対戦相手情報</h2>
      <div class="field">
        <p>相手のID（もしあれば）</p>
        <div><%= form.number_field :opponent_id %></div>
      </div>

      <div class="field">
        <p>名前</p>
        <div><%= form.number_field :opponent_id %></div>
      </div>

      <div class="field">
        <p>性別</p>
        <% Gender.all.each do |attr| %>
          <div>
            <%= form.radio_button 'gender_id', attr.id, {} %><%= attr.name %>
          </div>
        <% end %>
      </div>

      <div class="field">
        <p>級</p>
        <% Grade.all.each do |attr| %>
          <div>
            <%= form.radio_button 'grade_id', attr.id, {} %><%= attr.name %>
          </div>
        <% end %>
      </div>

      <div class="field">
        <p>利き腕</p>
        <% Hand.all.each do |attr| %>
          <div>
            <%= form.radio_button 'hand_id', attr.id, {} %><%= attr.name %>
          </div>
        <% end %>
      </div>

      <div class="field">
        <p>所属</p>
        <div><%= form.number_field :opponent_id %></div>
      </div>

      <div class="field">
        <p>かるたスタイル</p>
        <% Style.all.each do |attr| %>
          <div>
            <%= form.radio_button 'style_id', attr.id, {} %><%= attr.name %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="result-input-container comment">
      <h2>気づいたこと・指導内容・反省など（自由に）</h2>
      <div><%= form.text_area :comment %></div>
    </div>

    <div class="search-btn btn">
      <%= link_to '入力完了', new_tournament_path %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>

  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Gametype</th>
      <th>Gamecount</th>
      <th>Opponent</th>
      <th>Carddifference</th>
      <th>Comment</th>
      <th>Discussionopp</th>
      <th>Discussionself</th>
      <th>User</th>
      <th>Critical</th>
      <th>Avoidance</th>
      <th>Otetsuki</th>
      <th>Joker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.date %></td>
        <td><%= result.gameType_id %></td>
        <td><%= result.gameCount_id %></td>
        <td><%= result.opponent_id %></td>
        <td><%= result.cardDifference %></td>
        <td><%= result.comment %></td>
        <td><%= result.discussionOpp %></td>
        <td><%= result.discussionSelf %></td>
        <td><%= result.user_id %></td>
        <td><%= result.critical_id %></td>
        <td><%= result.avoidance_id %></td>
        <td><%= result.otetsuki_id %></td>
        <td><%= result.joker_id %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<div class="result-input-contents contents">
  <div class="column"></div>
  <div class="result-input-main main">
    <h1>試合結果入力（*がついている項目は入力必須項目）</h1>

    <%= render 'form', result: @result %>

    <%= link_to 'Back', results_path %>
  </div>
  <div class="right-column column"></div>
</div>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>
<div class="result-show-contents contents">
  <div class="column"></div>
  <div class="result-show-main main">
    <div class="result-show">
      <div class="result-show-container">
        <h2><%= @result.date.month %>月<%= @result.date.day %>日　<%= @result.gameCount_id %>試合目の試合結果</h2>
        
        <p>
          <strong>Gametype:</strong>
          <%= @result.gameType_id %>
        </p>

        <p>
          <strong>Gamecount:</strong>
          <%= @result.gameCount_id %>
        </p>

        <p>
          <strong>勝敗:</strong>
          <%= @result.cardDifference %>
        </p>

        <p>
          <strong>枚差:</strong>
          <%= @result.cardDifference %>
        </p>

      </div>
    </div>

    <p>
      <strong>Opponent:</strong>
      <%= @result.opponent_id %>
    </p>

    <p>
      <strong>Comment:</strong>
      <%= @result.comment %>
    </p>

    <p>
      <strong>Discussionopp:</strong>
      <%= @result.discussionOpp %>
    </p>

    <p>
      <strong>Discussionself:</strong>
      <%= @result.discussionSelf %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @result.user_id %>
    </p>

    <p>
      <strong>Critical:</strong>
      <%= @result.critical_id %>
    </p>

    <p>
      <strong>Avoidance:</strong>
      <%= @result.avoidance_id %>
    </p>

    <p>
      <strong>Otetsuki:</strong>
      <%= @result.otetsuki_id %>
    </p>

    <p>
      <strong>Joker:</strong>
      <%= @result.joker_id %>
    </p>
  </div>
</div>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>