config/routes.rb
Rails.application.routes.draw do
  resources :jokers
  resources :avoidances
  resources :otetsukis
  resources :criticals
  resources :grades_tournaments
  resources :districts
  resources :hands
  resources :genders
  resources :grades
  resources :age_classes
  resources :areas
  resources :styles
  resources :game_counts
  resources :game_types
  resources :fields
  resources :karuta
  resources :opponents
  resources :results
  resources :tournaments
  resources :schedule_tournaments
  resources :schedule_practices
  devise_for :users
  root 'pages#index'
  get 'pages/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/age_class.rb
class AgeClass < ApplicationRecord
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/avoidance.rb
class Avoidance < ApplicationRecord
  belongs_to :result
  belongs_to :karutum
end

app/models/critical.rb
class Critical < ApplicationRecord
  belongs_to :result
  belongs_to :karutum
  belongs_to :field
end

app/models/district.rb
class District < ApplicationRecord
end

app/models/field.rb
class Field < ApplicationRecord
  has_many :criticals
  has_many :results, :through => :criticals
  has_many :karutum, :through => :criticals
  has_many :otetsukis
  has_many :results, :through => :otetsukis
  has_many :karutum, :through => :otetsukis
end

app/models/game_count.rb
class GameCount < ApplicationRecord
    has_many :results
end

app/models/game_type.rb
class GameType < ApplicationRecord
    has_many :results
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :grades_tournaments
  has_many :tournaments, :through => :grades_tournaments
end

app/models/hand.rb
class Hand < ApplicationRecord
end

app/models/joker.rb
class Joker < ApplicationRecord
  belongs_to :result
  belongs_to :karuta
end

app/models/karutum.rb
class Karutum < ApplicationRecord
    has_many :avoidances
    has_many :results, :through => :avoidances
    has_many :jokers
    has_many :results, :through => :jokers
    has_many :criticals
    has_many :results, :through => :criticals
    has_many :fields, :through => :criticals
    has_many :otetsukis
    has_many :results, :through => :otetsukis
    has_many :fields, :through => :otetsukis
end

app/models/opponent.rb
class Opponent < ApplicationRecord
    has_many :results
    belongs_to :style
    belongs_to :gender
    belongs_to :hand
    belongs_to :ageClass
end

app/models/otetsuki.rb
class Otetsuki < ApplicationRecord
  belongs_to :result
  belongs_to :karutum
  belongs_to :field
end

app/models/result.rb
class Result < ApplicationRecord
    has_many :avoidances, dependent: :destroy
    has_many :karuta, :through => :avoidances
    accepts_nested_attributes_for :avoidances, allow_destroy: true
    has_many :jokers, dependent: :destroy
    has_many :karuta, :through => :jokers
    accepts_nested_attributes_for :jokers, allow_destroy: true
    has_many :criticals, dependent: :destroy
    has_many :karuta, :through => :criticals
    has_many :fields, :through => :criticals
    accepts_nested_attributes_for :criticals, allow_destroy: true
    has_many :otetsukis, dependent: :destroy
    has_many :karuta, :through => :otetsukis
    has_many :fields, :through => :otetsukis
    accepts_nested_attributes_for :otetsukis, allow_destroy: true
    belongs_to :gameType
    belongs_to :gameCount
    belongs_to :opponent
    belongs_to :user
end

app/models/schedule_practice.rb
class SchedulePractice < ApplicationRecord
end

app/models/style.rb
class Style < ApplicationRecord
    has_many :opponents
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  default_scope -> { order(date: :asc) }
  has_many :grades_tournament
  has_many :tournaments, :through => :grades_tournament
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/schedule_practices_controller.rb
class SchedulePracticesController < ApplicationController
  before_action :set_schedule_practice, only: [:show, :edit, :update, :destroy]

  # GET /schedule_practices
  # GET /schedule_practices.json
  def index
    @schedule_practices = SchedulePractice.all
  end

  # GET /schedule_practices/1
  # GET /schedule_practices/1.json
  def show
  end

  # GET /schedule_practices/new
  def new
    @schedule_practice = SchedulePractice.new
  end

  # GET /schedule_practices/1/edit
  def edit
  end

  # POST /schedule_practices
  # POST /schedule_practices.json
  def create
    @schedule_practice = SchedulePractice.new(schedule_practice_params)

    respond_to do |format|
      if @schedule_practice.save
        format.html { redirect_to @schedule_practice, notice: 'Schedule practice was successfully created.' }
        format.json { render :show, status: :created, location: @schedule_practice }
      else
        format.html { render :new }
        format.json { render json: @schedule_practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedule_practices/1
  # PATCH/PUT /schedule_practices/1.json
  def update
    respond_to do |format|
      if @schedule_practice.update(schedule_practice_params)
        format.html { redirect_to @schedule_practice, notice: 'Schedule practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule_practice }
      else
        format.html { render :edit }
        format.json { render json: @schedule_practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedule_practices/1
  # DELETE /schedule_practices/1.json
  def destroy
    @schedule_practice.destroy
    respond_to do |format|
      format.html { redirect_to schedule_practices_url, notice: 'Schedule practice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule_practice
      @schedule_practice = SchedulePractice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_practice_params
      params.require(:schedule_practice).permit(:start_time, :place, :note, :user_id)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/schedule_practices_helper.rb
module SchedulePracticesHelper
end

app/views/schedule_practices/_form.html.erb
<%= form_with(model: schedule_practice, local: true) do |form| %>
  <% if schedule_practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule_practice.errors.count, "error") %> prohibited this schedule_practice from being saved:</h2>

      <ul>
      <% schedule_practice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedule_practices/edit.html.erb
<h1>Editing Schedule Practice</h1>

<%= render 'form', schedule_practice: @schedule_practice %>

<%= link_to 'Show', @schedule_practice %> |
<%= link_to 'Back', schedule_practices_path %>

app/views/schedule_practices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedule Practices</h1>

<%= month_calendar events: @schedule_practices do |date, schedule_practices| %>
  <%= date %>
  <% puts "-----------------------" %>
  <% puts schedule_practices %>
  <% puts "-----------------------" %>
  <% schedule_practices.each do |schedule_practice| %>
    <div>
      <%= schedule_practice.place %>
    </div>
  <% end %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Place</th>
      <th>Note</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @schedule_practices.each do |schedule_practice| %>
      <tr>
        <td><%= schedule_practice.start_time %></td>
        <td><%= schedule_practice.place %></td>
        <td><%= schedule_practice.note %></td>
        <td><%= schedule_practice.user_id %></td>
        <td><%= link_to 'Show', schedule_practice %></td>
        <td><%= link_to 'Edit', edit_schedule_practice_path(schedule_practice) %></td>
        <td><%= link_to 'Destroy', schedule_practice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Schedule Practice', new_schedule_practice_path %>

app/views/schedule_practices/new.html.erb
<h1>New Schedule Practice</h1>

<%= render 'form', schedule_practice: @schedule_practice %>

<%= link_to 'Back', schedule_practices_path %>

app/views/schedule_practices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @schedule_practice.start_time %>
</p>

<p>
  <strong>Place:</strong>
  <%= @schedule_practice.place %>
</p>

<p>
  <strong>Note:</strong>
  <%= @schedule_practice.note %>
</p>

<p>
  <strong>User:</strong>
  <%= @schedule_practice.user_id %>
</p>

<%= link_to 'Edit', edit_schedule_practice_path(@schedule_practice) %> |
<%= link_to 'Back', schedule_practices_path %>